# Generated by Django 4.2.2 on 2023-06-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('CustomerId', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Surname', models.CharField(max_length=50, null=True)),
                ('CreditScore', models.IntegerField(null=True)),
                ('Geography', models.CharField(max_length=50, null=True)),
                ('Gender', models.CharField(max_length=10, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Tenure', models.IntegerField(null=True)),
                ('Balance', models.FloatField(null=True)),
                ('NumOfProducts', models.IntegerField(null=True)),
                ('HasCrCard', models.IntegerField(null=True)),
                ('IsActiveMember', models.IntegerField(null=True)),
                ('EstimatedSalary', models.FloatField(null=True)),
                ('Exited', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
